# Generated by Django 4.1.1 on 2022-11-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_payment_created_alter_payment_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
