# Generated by Django 4.1.1 on 2022-11-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='billing_address',
            field=models.CharField(max_length=50),
        ),
    ]
